/*Enable user creation*/
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
/* Create a user named “USER_S4663588” with password “w” */
CREATE USER USER_S4663588 IDENTIFIED BY w ACCOUNT UNLOCK DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" PROFILE "DEFAULT";
/* Grant DBA privilege to “USER_S4663588” */
GRANT DBA TO USER_S4663588;
/* Check if “USER_S4663588” has been created */
SELECT USERNAME FROM DBA_USERS;