(1)

SELECT COUNT(*) 
FROM ATHLETE2 
WHERE CCODE = 'AUS';

(2)

SELECT SPORTID AS Sport_ID, COUNT(*) AS Count 
FROM ATHLETE3 
WHERE CCODE = 'RUS' 
GROUP BY SPORTID;

(3)

CREATE TABLE ATHLETE_FULL(
	ATHLETEID NUMBER NOT NULL,
	FNAME VARCHAR2(30 BYTE),
	SNAME VARCHAR2(30 BYTE),
	BDATE VARCHAR2(30 BYTE),
	CCODE VARCHAR2(30 BYTE),
	SPORTID NUMBER
);

INSERT INTO ATHLETE_FULL 
SELECT * FROM ATHLETE1 
UNION ALL 
SELECT * FROM ATHLETE2 
UNION ALL 
SELECT * FROM ATHLETE3;

SELECT COUNT(ATHLETE_FULL.ATHLETEID) 
FROM ATHLETE_FULL, COUNTRY 
WHERE ATHLETE_FULL.CCODE = COUNTRY.CCODE 
	AND COUNTRY.CONTINENT = 'EU';

